name = "Hype Home Modpack"
author = "Joe"
version = "0.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fe267f16f1e64186513f11fe57b53dabecf43b96b1456eaec466001d3da2906"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17.1", "1.17"]
