name = "Hype Home Modpack"
author = "Joe"
version = "0.1.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73f4cc3a493eebfb89c2db1f970829ea7220dcc0cf1203abfdf955740242beca"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17.1", "1.17"]
